export type ToolpathGroup = {
  color?: string;
  label?: string;
  runs?: number[][];
};

export type GCodeOptions = {
  penUp?: number;
  penDown?: number;
  drawFeed?: number;
  travelFeed?: number;
  zFeed?: number;
  name?: string;
  machine?: string;
  origin?: "rear-left" | "bottom-left";
  effects?: Partial<Record<"halftone" | "chroma" | "humanizer" | "blueprint", boolean>>;
};

const clampPrecision = (value: number) => {
  const rounded = Math.round(value * 1000) / 1000;
  return Object.is(rounded, -0) ? "0" : String(rounded);
};

const cleanComment = value => String(value ?? "").replace(/[()\r\n]/g, " ").trim();

function finiteOption(value: unknown, fallback: number, {positive = false}: { positive?: boolean } = {}) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || (positive && parsed <= 0)) return fallback;
  return parsed;
}

function prepareRun(run: number[], height: number, origin: GCodeOptions["origin"]) {
  const points = [];
  for (let i = 0; i + 1 < run.length; i += 2) {
    const x = Number(run[i]);
    const sourceY = Number(run[i + 1]);
    const y = origin === "rear-left" ? sourceY : height - sourceY;
    if (!Number.isFinite(x) || !Number.isFinite(y)) continue;
    const previous = points[points.length - 1];
    if (!previous || Math.hypot(x - previous[0], y - previous[1]) > 0.0005) points.push([x, y]);
  }
  return points.length > 1 ? points : null;
}

function orderRuns(runs: number[][][]) {
  const remaining = runs.slice();
  const ordered = [];
  let cursor = [0, 0];
  while (remaining.length) {
    let bestIndex = 0;
    let reverse = false;
    let bestDistance = Infinity;
    for (let i = 0; i < remaining.length; i++) {
      const run = remaining[i];
      const startDistance = Math.hypot(run[0][0] - cursor[0], run[0][1] - cursor[1]);
      const end = run[run.length - 1];
      const endDistance = Math.hypot(end[0] - cursor[0], end[1] - cursor[1]);
      if (startDistance < bestDistance) {
        bestDistance = startDistance;
        bestIndex = i;
        reverse = false;
      }
      if (endDistance < bestDistance) {
        bestDistance = endDistance;
        bestIndex = i;
        reverse = true;
      }
    }
    const [next] = remaining.splice(bestIndex, 1);
    if (reverse) next.reverse();
    ordered.push(next);
    cursor = next[next.length - 1];
  }
  return ordered;
}

/** Convert contour polyline groups into conservative, controller-neutral plotter G-code. */
export function generateGCode(groups: ToolpathGroup[], sheet: { width?: number; height?: number }, options: GCodeOptions = {}) {
  const width = finiteOption(sheet?.width, 210, {positive: true});
  const height = finiteOption(sheet?.height, 210, {positive: true});
  const penUp = finiteOption(options.penUp, 5);
  const penDown = finiteOption(options.penDown, 0);
  const drawFeed = finiteOption(options.drawFeed, 1200, {positive: true});
  const travelFeed = finiteOption(options.travelFeed, 3000, {positive: true});
  const zFeed = finiteOption(options.zFeed, 600, {positive: true});
  const name = cleanComment(options.name || "contours");
  const machine = cleanComment(options.machine || "Generic Z-axis plotter");
  const origin = options.origin === "rear-left" ? "rear-left" : "bottom-left";
  const effects = options.effects || {};
  const usableGroups = (groups || []).map(group => ({
    color: cleanComment(group.color || "unspecified"),
    label: cleanComment(group.label || "contours"),
    runs: orderRuns((group.runs || []).map(run => prepareRun(run, height, origin)).filter(Boolean)),
  })).filter(group => group.runs.length);

  const lines = [
    "; Generated by Slicewise",
    `; Source: ${name}`,
    `; Machine: ${machine}`,
    `; Sheet: ${clampPrecision(width)} x ${clampPrecision(height)} mm`,
    origin === "rear-left" ? "; Origin: rear-left of sheet; +X right; +Y toward front" : "; Origin: bottom-left of sheet; +X right; +Y up",
  ];
  if (effects.halftone) lines.push("; Note: SVG dash styling is exported as continuous plotter paths");
  if (effects.chroma) lines.push("; Note: chromatic SVG offsets are exported as one base contour set");
  if (effects.humanizer) lines.push("; Humanizer: hand-drawn variations are included in these toolpaths");
  if (effects.blueprint) lines.push("; Note: blueprint border and annotations are SVG-only; G-code contains the base contour set");
  lines.push("G21 ; millimetres", "G90 ; absolute positioning", "G94 ; feed per minute", `G1 Z${clampPrecision(penUp)} F${clampPrecision(zFeed)} ; pen up`);

  let tool = 0;
  for (const group of usableGroups) {
    tool += 1;
    lines.push(`; Tool ${tool}: ${group.label}, ${group.color}`);
    if (tool > 1) lines.push(`M0 ; change pen to ${group.color}`);
    for (const run of group.runs) {
      const [start, ...points] = run;
      lines.push(
        `G0 X${clampPrecision(start[0])} Y${clampPrecision(start[1])} F${clampPrecision(travelFeed)}`,
        `G1 Z${clampPrecision(penDown)} F${clampPrecision(zFeed)} ; pen down`,
      );
      for (const point of points) lines.push(`G1 X${clampPrecision(point[0])} Y${clampPrecision(point[1])} F${clampPrecision(drawFeed)}`);
      lines.push(`G1 Z${clampPrecision(penUp)} F${clampPrecision(zFeed)} ; pen up`);
    }
  }
  lines.push(`G0 X0 Y0 F${clampPrecision(travelFeed)}`, "M2", "");
  return lines.join("\n");
}
