import { type ContourSettings } from './contour-engine';

type RuntimeOnlySetting =
  'documentTitle' | 'lens' | 'lensAmount' | 'previewDetail' | 'suppressBackground';

export type RenderSettingKey = Exclude<keyof ContourSettings, RuntimeOnlySetting>;
export type RenderSettingsSource = Omit<ContourSettings, 'documentTitle' | 'suppressBackground'> & {
  name: string;
};

/**
 * Settings copied into every worker request. The compile-time exhaustiveness
 * check makes additions to ContourSettings deliberate at this boundary.
 */
export const renderSettingKeys = [
  'az',
  'el',
  'roll',
  'zoom',
  'panX',
  'panY',
  'lensFocalLength',
  'lensPerspective',
  'lensWarpExponent',
  'lensDistortion',
  'projectionWarpMode',
  'mobiusDirection',
  'mobiusDisplacement',
  'mobiusRotation',
  'mobiusStrength',
  'sphericalStrength',
  'inversionCenterX',
  'inversionCenterY',
  'inversionRadius',
  'inversionStrength',
  'tilingP',
  'tilingQ',
  'tilingDepth',
  'tilingDiskScale',
  'lines',
  'gapEase',
  'easeStrength',
  'easeCycles',
  'easeCenter',
  'quality',
  'axis',
  'cutAz',
  'cutEl',
  'waveCenterX',
  'waveCenterY',
  'waveCenterZ',
  'cylinderAzimuth',
  'cylinderElevation',
  'geodesicSeedAzimuth',
  'geodesicSeedElevation',
  'geodesicMode',
  'geodesicSeedBAzimuth',
  'geodesicSeedBElevation',
  'curvatureMethod',
  'curvatureSmoothing',
  'curvatureRange',
  'curvatureContrast',
  'curvatureIncludeZero',
  'divergence',
  'sliceLfo',
  'sliceLfoAmplitude',
  'sliceLfoCycles',
  'sliceLfoAngle',
  'sliceLfoPhase',
  'sliceLfoWaveform',
  'sliceLfoModulation',
  'sliceLfoModulationMode',
  'sliceLfoModulationDepth',
  'sliceLfoModulationCycles',
  'sliceLfoModulationPhase',
  'explodeAmount',
  'blockGlitch',
  'blockGlitchCount',
  'blockGlitchWidth',
  'blockGlitchHeight',
  'blockGlitchDisplacement',
  'blockGlitchDirection',
  'blockGlitchClearDestination',
  'blockGlitchSeed',
  'scanBandGlitch',
  'scanBandGlitchCount',
  'scanBandGlitchThickness',
  'scanBandGlitchDisplacement',
  'scanBandGlitchDensity',
  'scanBandGlitchOrientation',
  'scanBandGlitchSeed',
  'staggeredSlices',
  'staggeredSlicesCount',
  'staggeredSlicesExtent',
  'staggeredSlicesDisplacement',
  'staggeredSlicesOrientation',
  'staggeredSlicesPattern',
  'staggeredSlicesSeed',
  'wraparoundTear',
  'wraparoundTearOrientation',
  'wraparoundTearPosition',
  'wraparoundTearSize',
  'wraparoundTearShift',
  'tileShuffle',
  'tileShuffleRows',
  'tileShuffleColumns',
  'tileShuffleExtent',
  'tileShuffleAffected',
  'tileShuffleSeed',
  'sampleAndHold',
  'sampleAndHoldAxis',
  'sampleAndHoldSpacing',
  'sampleAndHoldLength',
  'sampleAndHoldMix',
  'misregistration',
  'misregistrationCopies',
  'misregistrationOffset',
  'misregistrationRotation',
  'misregistrationScope',
  'misregistrationColor1',
  'misregistrationColor2',
  'misregistrationColor3',
  'kaleidoscope',
  'kaleidoscopeSegments',
  'kaleidoscopeRotation',
  'spiral',
  'hide',
  'sil',
  'sw',
  'lineWeightMode',
  'lineWeightInterval',
  'lineWeightAmount',
  'color',
  'backgroundColor',
  'gradientEnabled',
  'gradientColors',
  'gradientStops',
  'lineIndexColorEnabled',
  'lineIndexColors',
  'pw',
  'ph',
  'margin',
  'clipToArtboard',
  'maskEnabled',
  'maskOutline',
  'maskRoundness',
  'maskScaleX',
  'maskScaleY',
  'maskOffsetX',
  'maskOffsetY',
  'maskLfo1Amplitude',
  'maskLfo1Cycles',
  'maskLfo1Phase',
  'maskLfo1Waveform',
  'maskLfo2Amplitude',
  'maskLfo2Cycles',
  'maskLfo2Phase',
  'maskLfo2Waveform',
  'bg',
  'halftone',
  'halftoneSize',
  'halftoneContrast',
  'halftoneCycles',
  'chroma',
  'chromaAmount',
  'humanizer',
  'humanizerAmount',
  'yarnCurl',
  'yarnCutPercent',
  'yarnCurlSize',
  'blueprint',
  'blueprintStyle',
  'topographicMap',
  'vectorZoom1Enabled',
  'vectorZoom1Shape',
  'vectorZoom1CenterX',
  'vectorZoom1CenterY',
  'vectorZoom1Width',
  'vectorZoom1Height',
  'vectorZoom1Corner',
  'vectorZoom1Size',
  'vectorZoom1Margin',
  'vectorZoom1Color',
  'vectorZoom2Enabled',
  'vectorZoom2Shape',
  'vectorZoom2CenterX',
  'vectorZoom2CenterY',
  'vectorZoom2Width',
  'vectorZoom2Height',
  'vectorZoom2Corner',
  'vectorZoom2Size',
  'vectorZoom2Margin',
  'vectorZoom2Color',
  'vectorZoom3Enabled',
  'vectorZoom3Shape',
  'vectorZoom3CenterX',
  'vectorZoom3CenterY',
  'vectorZoom3Width',
  'vectorZoom3Height',
  'vectorZoom3Corner',
  'vectorZoom3Size',
  'vectorZoom3Margin',
  'vectorZoom3Color',
  'vectorZoom4Enabled',
  'vectorZoom4Shape',
  'vectorZoom4CenterX',
  'vectorZoom4CenterY',
  'vectorZoom4Width',
  'vectorZoom4Height',
  'vectorZoom4Corner',
  'vectorZoom4Size',
  'vectorZoom4Margin',
  'vectorZoom4Color',
  'morphEnabled',
  'morphSteps',
  'morphTargets',
  'morphSecondEnabled',
  'morphStepsY',
  'morphTargets2',
] as const satisfies readonly RenderSettingKey[];

type MissingRenderSetting = Exclude<RenderSettingKey, (typeof renderSettingKeys)[number]>;
const allRenderSettingsAreListed: [MissingRenderSetting] extends [never] ? true : never = true;
void allRenderSettingsAreListed;

export function createRenderSettingsSnapshot(source: RenderSettingsSource): ContourSettings {
  const entries = renderSettingKeys.map((key) => [key, source[key]] as const);
  const snapshot = Object.fromEntries(entries) as unknown as ContourSettings;
  snapshot.documentTitle = source.name;
  snapshot.morphTargets = { ...source.morphTargets };
  snapshot.morphTargets2 = { ...source.morphTargets2 };
  return snapshot;
}
